wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.10
    is_jupyter_run: true
    python_version: 3.7.3
look_back:
  desc: null
  value: 20
repeated_predictions:
  desc: null
  value: false
